---
# Set up iterm2
- name: Check for iterm zsh integration
  stat: 
    path: ~/.iterm2_shell_integration.zsh
  register: zsh_integrations

- name: Pull zsh iterm2 integrations if necessary
  command: curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
  when: not zsh_integrations.stat.exists

- name: Check for iterm bash integration
  stat:
    path: ~/.iterm2_shell_integration.bash
  register: bash_integrations

- name: Pull bash iterm2 integrations if necessary
  command: curl -L https://iterm2.com/shell_integration/bash -o ~/.iterm2_shell_integration.bash
  when: not bash_integrations.stat.exists
