---
- name: Ensure vs code is installed by check for the cli
  stat:
    path: /opt/homebrew/bin/code
  register: stat_result

- name: Install VS Code extensions
  command: "/opt/homebrew/bin/code --install-extension {{ item }}"
  loop:
    - "{{ vscode_extensions }}"
  when: stat_result.stat.exists
